variables:
  # DJANGO_CONFIG: "test"
  NORM_POSTGRES_DATABASE: $NORM_POSTGRES_DATABASE
  NORM_POSTGRES_USER: $NORM_POSTGRES_USER
  NORM_POSTGRES_PASSWORD: $NORM_POSTGRES_PASSWORD
  SSH_PRIVKEY_FOR_FORM_HENDRICKSENPHD_COM: $SSH_PRIVKEY_FOR_FORM_HENDRICKSENPHD_COM
  USERNAME: $USERNAME
  DEPLOY_TOKEN: $DEPLOY_TOKEN
  TZ: "America/Los_Angeles"

default:
  image: ubuntu:latest
  before_script:
    - echo 'Doing things...'

#connect_to_postgres:
#  image: postgres
#  script:
#  # official way to provide password to psql: http://www.postgresql.org/docs/9.3/static/libpq-envars.html
#  - export PGPASSWORD=$NORM_POSTGRES_PASSWORD
#  - psql -h "postgres" -U "$NORM_POSTGRES_USER" -d "$NORM_POSTGRES_DATABASE" -c "SELECT 'OK' AS status;"

stages:
  - deploy

setup_docker_container_and_deploy:
  stage: deploy
  script:
    - export TZ=America/Los_Angeles
    - export DEBIAN_FRONTEND=noninteractive
    - apt -y update
    - apt -y upgrade
    - apt -y install apt-utils
    - apt -y install net-tools postgresql openssh-server openssh-client git
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - touch ~/.ssh/id_rsa
    - echo 'Set form.hendricksenphd.com privkey'
    - echo "$SSH_PRIVKEY_FOR_FORM_HENDRICKSENPHD_COM" | ssh-add - > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa
    - ssh-keyscan -p 2986 form.hendricksenphd.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git config --global user.email "chausse@gmail.com"
    - git config --global user.name "Ryan Chausse"
    - echo 'try to connect to form.hendricksenphd.com'
    #- ssh -i ~/.ssh/id_rsa root@form.hendricksenphd.com
    #  "cd /var/www;
    #  git clone https://$USERNAME:$DEPLOY_TOKEN@code.ryanchausse.com/ryanchausse/norm.git;"
    - ssh -v -i ~/.ssh/id_rsa chausse@form.hendricksenphd.com -p 2986
      "hostname;
      ssh-keyscan code.ryanchausse.com >> ~/.ssh/known_hosts;
      chmod 644 ~/.ssh/known_hosts;
      echo 'Pulling norm repo';
      cd /var/www/norm;
      git config --global --add safe.directory "/var/www/norm";
      whoami;
      pwd;
      ssh -Tv git@code.ryanchausse.com;
      git pull;
      apt install -y python3-pip;
      pip3 install virtualenv;
      virtualenv venv_norm;
      source venv_norm/bin/activate;
      pip3 install -r requirements.txt;
      python3 manage.py makemigrations;
      python3 manage.py migrate;
      python3 manage.py check;
      python3 manage.py test;
      python3 manage.py collectstatic --no-input;
      service apache2 restart;
      deactivate;"
    # Might want to chown -R www-data:www-data /var/www; in the future, but do not. Beware of root owned admin directory
    - echo "Great success."

